apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config-flask
  namespace: flask-app
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Log_Level     info
        Daemon        off
        Parsers_File  parsers.conf

    [INPUT]
        Name              tail
        Path              /var/log/app/flask-app.log
        Parser            json
        Tag               flask-app
        Refresh_Interval  5
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On

    [OUTPUT]
        Name                loki
        Match               *
        Host                loki-gateway.loki.svc.cluster.local
        Port                80
        Labels              job=flask-app,tenant=flask-tenant
        tenant_id           flask-tenant
        
  parsers.conf: |
    [PARSER]
        Name        json
        Format      json
        Time_Key    timestamp
        Time_Format %Y-%m-%dT%H:%M:%S.%LZ
        Time_Keep   On
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluent-bit-flask
  namespace: flask-app
spec:
  selector:
    matchLabels:
      k8s-app: fluent-bit-flask
  template:
    metadata:
      labels:
        k8s-app: fluent-bit-flask
    spec:
      serviceAccount: fluent-bit-flask
      containers:
      - name: fluent-bit
        image: fluent/fluent-bit:2.1.8
        volumeMounts:
        - name: config
          mountPath: /fluent-bit/etc/
        - name: app-logs
          mountPath: /var/log/app
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
      volumes:
      - name: config
        configMap:
          name: fluent-bit-config-flask
      - name: app-logs
        hostPath:
          path: /var/log/flask-app
          type: DirectoryOrCreate
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluent-bit-flask
  namespace: flask-app